### ISSUE TITLE
Support for latest Clang versions

### ISSUE THREAD

**Issue by yutsareva** [aflnet/aflnet#113]
Hi there,

Really cool project! I'm interested in using AFLNet, but it seems limited to Clang 12. Are there plans to extend support to newer Clang versions or to integrate with AFL++?

Thanks

**Comment by mboehme** [comment]
Not sure if @thuanpv's group currently has any plans, but what I can definitely say is that we are always looking for pull requests to improve AFLNet.

**Comment by thuanpv** [comment]
Hi @yutsareva. Thanks for your interest. Have you managed to solve that issue? If so, a PR is welcome. Otherwise, we will try our best to solve that when we have time but can't promise anything as you may know we keep working on new projects as researchers and may not be able to keep everything up to date.

**Comment by thuanpv** [comment]
FYI, I have just tested the mainstream AFL at https://github.com/google/AFL with clang-14 and it seems that it also has the issue. So definitely it is not AFLNet specific.
