### ISSUE TITLE
M2_start_region_ID wrong?

### ISSUE THREAD

**Issue by acidghost** [aflnet/aflnet#13]
Hi there,

by reading the paper I understand that, for mutation, the original sequence `M` is split into 3:
- `M1` is the prefix needed to *reach* the target state `s` (i.e. transitions `a->b->s`;
- `M2` is the sub-sequence that remains in `s` (i.e. transitions like `s->s`);
- `M3` is the leftover (i.e. `s->x->y`).

Mutation is then applied only on `M2` so that `M'` (the mutated sequence) still reaches `s` (e.g. if `M=<m1,m2,m3>` exercises `a->s->b`, `M'=<m1,m2',m3>` should still result in a sequence of states starting in `a->s`).

Instead, https://github.com/aflnet/aflnet/blob/e2a6b2d802429033f320c58fc38d4ad201461073/afl-fuzz.c#L5892-L5903 seems to set `M2_start_region_ID` to the index of the region that *reaches* the target state, instead of the one right after; in other words, it looks like `M2_start_region_ID` is set to the index of the last region of `M1`.

**Comment by thuanpv** [comment]
Hi @acidghost,

Thank you for your question.

I would like to clarify how a whole message sequence M is split. In our paper, we said: "Given a state s and a message sequence M, AFLNet generates a new sequence M' by mutation. In order to ensure that the mutated sequence M' still exercises the chosen states, AFLNet splits the original sequence M into three parts: 1) the prefix M1 is required to reach the selected state s,
2) the candidate subsequence M2 contains all messages that can be executed after M1 while still remaining in s, and 3) the suffix M3 is simply the left-over subsequence such that <M1, M2, M3> = M. The mutated message sequence M' = <M1, mutate(M2), M3>. By maintaining the original subsequence M1, M' will still reach the state s which is the state that the fuzzer is currently focusing on". So I would correct your first part as below.

- M1 is the prefix needed to reach the target state s (i.e. transitions a->b->s); after receiving M1, the server under test (SUT) should reach state s.
- M2 is the sub-sequence *that is sent to the SUT while it still remains in state s* (i.e. transitions like s->s->...->s->c while c can be s or another state). It means that the SUT should consume the whole subsequence M2 while it is in state s; however, it can reach another state c where c could be s or something else.
- M3 is the leftover (i.e. c->x->y).

Do you think based on this the algorithm makes sense now? Note that the region ID starts from 0.

Thuan

**Comment by acidghost** [comment]
Thank you for the clarification, but I still see the problem.

Let me exemplify with some data from a real run. I was trying the LightFTP tutorial setting and made changes to AFLnet to dump the target state, the chosen seed and `M2_start_region_ID` for every invocation of `fuzz_one`.

At one point the fuzzer selects target state `331` and `M2_start_region_ID=0` for the following seed:

```
❯ hd out-lightftp/queue/id:000140,src:000000,op:havoc,rep:16,+cov
00000000  55 53 45 52 20 61 6e 6f  6e 79 6d 6f 75 73 0d 0a  |USER anonymous..|
00000010  50 41 53 53 20 75 62 75  6e 74 75 0d 0a 10 4d 4c  |PASS ubuntu...ML|
00000020  53 44 00 53 53 20 75 62  75 6e 05 ff ff 05 53 4e  |SD.SS ubun....SN|
00000030  4f 4f 50 75 0d 0a 53 59  00 00 01 0d 01 0d 80 57  |OOPu..SY.......W|
00000040  41 53 53 20 75 62 75 6e  74 75 0d 0a 53 59 00 00  |ASS ubuntu..SY..|
00000050  20 0d 01 0d 80 10 4d 4c  53 44 00 53 53 20 75 00  | .....MLSD.SS u.|
00000060  00 03 e8 ff ff 05 53 4e  4f 4f 50 75 0d 0a 53 59  |......SNOOPu..SY|
00000070  00 00 01 0c ec 0d 80 50  41 53 53 20 75 62 75 6e  |.......PASS ubun|
00000080  74 75 0d 0a 53 59 00 00  20 0d 01 0d 80 50 57 44  |tu..SY.. ....PWD|
00000090  0d 0a 50 4f 52 54 20 31  32 37 2c 30 2c 30 2c 31  |..PORT 127,0,0,1|
000000a0  2c 31 35 32 2c 31 39 33  0d 0a 4c 49 53 54 0d 0a  |,152,193..LIST..|
000000b0  51 55 49 54 0d 0a                                 |QUIT..|
000000b6
```

This means that all mutants will have `M1` empty. How can an empty `M1` make the mutants reach state `331` without sending the `USER anonymous\r\n` message/region? It is my understanding that `M2_start_region_ID` should be 1 in this case, so that `M1` contains the `USER` command.

**Comment by acidghost** [comment]
More specifically:
- `q->regions[0]` refers to the `USER` message and its `state_sequence` should contain `220,331`;
- `q->regions[1]` refers to the `PASS` message and its `state_sequence` should be `220,331,230`;
- ...

Considering, again, the following:
https://github.com/aflnet/aflnet/blob/e2a6b2d802429033f320c58fc38d4ad201461073/afl-fuzz.c#L5892-L5903
the loop will `break` when `i=0` and `M2_start_region_ID=0` because
`q->regions[0].state_sequence[last] == 331 == target_state_id`.

**Comment by thuanpv** [comment]
Thanks, @acidghost for reporting the issue and suggesting the patch. I have debugged the code and came up with the same patch. See the new commit 888add9. I close this issue now but please feel free to re-open it.
