### ISSUE TITLE
A issue consultation for aflnet

### ISSUE THREAD

**Issue by Nancy823** [aflnet/aflnet#46]
Hello,  I am very interested in the application extension of alfnet. And I use afl-g++ to achieve target service instrumented.  
However, there is a problem, that could be to get your help.  I searched the solutions for this issue from internet,  they said it might be afl-g++’s bug.  If changed to using afl-clang/afl-clang++,  that could be fine. 

But what I need that afl-g++ belongs to using CC which is gcc8.2,   the reason that our target service and depended sub-modules are compiled with gcc8.2.
So we need to combine afl-g++(that belongs to gcc8.2) with gcc8.2 for our target service instrumented. It could be occur this issue as follows, 

`/home/opt/compiler/gcc-8.2/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: bc_out/baidu/undb/meta/output/lib/libdalton-meta.a(baidu_undb_meta_dalton-meta_lib_undb_meta_client_service.cpp.o): TLS transition from R_X86_64_TLSGD to R_X86_64_GOTTPOFF against _ZN4bvar6detail10AgentGroupINS0_13AgentCombinerIjjNS0_5AddToIjEEE5AgentEE13_s_tls_blocksE' at 0xfb3f in section .text' failed /home/opt/compiler/gcc-8.2/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: nonrepresentable section on output collect2: error: ld returned 1 exit status`

I really sincerely consult to the solution for our case . Looking forward to yours reply.

**Comment by thuanpv** [comment]
Hi @Nancy823,

Based on my understanding, the issue is related to the compiler (Gcc/clang) version. Unfortunately, we don't have time to help you fix such system-specific issues. As stated in the README, we have tested AFLNet on standard Ubuntu 16.04 and Ubuntu 18.04 in which Clang versions are 3.8 and 6.0, respectively. We haven't tested it on other environments so there might be some compatibility issues like the one you reported. 

Regards,
Thuan
