### ISSUE TITLE
Unable to see AFLNet's options.

### ISSUE THREAD

**Issue by chengzicmj** [aflnet/aflnet#96]
Why does the command `afl-fuzz --help` not display AFLNet's options after restarting after a successful installation? （Before restarting, there is aflnet option, and the aflnet test protocol can be used normally）Does this mean that the installation failed? But after I reinstalled, I still can't see AFLNet's options using `afl-fuzz --help`.
![image](https://user-images.githubusercontent.com/48848996/234745545-90190e6d-b391-4d13-ae2c-217f4e4bc7fe.png)

**Comment by SaganCs** [comment]
I also encountered this problem, and I tried to reinstall it, but I have not tested a virtual machine. Did you solve this problem?

**Comment by chengzicmj** [comment]
Hello! I have solved this problem, instead of using `export PATH=$PATH:$AFLNET`, use `export PATH=$AFLNET:$PATH`. Hope can help you!




ccc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflnet/aflnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月7日(星期天) 中午1:16
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96)





 
I also encountered this problem, and I tried to reinstall it, but I have not tested a virtual machine. Did you solve this problem?

**Comment by SaganCs** [comment]
> Hello! I have solved this problem, instead of using `export PATH=$PATH:$AFLNET`, use `export PATH=$AFLNET:$PATH`. Hope can help you! ccc ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aflnet/aflnet" ***@***.***&gt;; 发送时间:&nbsp;2023年5月7日(星期天) 中午1:16 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96) I also encountered this problem, and I tried to reinstall it, but I have not tested a virtual machine. Did you solve this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Thank you for your suggestion. I have also successfully solved this problem

**Comment by chengzicmj** [comment]
OK! But this setting will cause new problems when testing lightftp, as shown in the picture below. At this time, you need to modify `export PATH=$AFLNET:$PATH` to `export PATH=$PATH:$AFLNET`. After executing `make`, you need to modify it to `export PATH=$AFLNET:$PATH`. Good luck!



ccc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflnet/aflnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 上午10:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96)





  
Hello! I have solved this problem, instead of using export PATH=$PATH:$AFLNET, use export PATH=$AFLNET:$PATH. Hope can help you! ccc @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aflnet/aflnet" @.&gt;; 发送时间:&nbsp;2023年5月7日(星期天) 中午1:16 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96) I also encountered this problem, and I tried to reinstall it, but I have not tested a virtual machine. Did you solve this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
Thank you for your suggestion. I have also successfully solved this problem

**Comment by SaganCs** [comment]
What a strange setting! This sounds like AFLNet has to be reset every time it is used on a new object.&nbsp;


银
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月8日(星期一) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aflnet/aflnet] Unable to see AFLNet&#39;s options. (Issue #96)





 OK! But this setting will cause new problems when testing lightftp, as shown in the picture below. At this time, you need to modify `export PATH=$AFLNET:$PATH` to `export PATH=$PATH:$AFLNET`. After executing `make`, you need to modify it to `export PATH=$AFLNET:$PATH`. Good luck! 
 
 
 
 ccc 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "aflnet/aflnet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年5月8日(星期一) 上午10:00 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96) 
 
 
 
 
 
    
 Hello! I have solved this problem, instead of using export PATH=$PATH:$AFLNET, use export PATH=$AFLNET:$PATH. Hope can help you! ccc @.*** &amp;nbsp; 
  … 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "aflnet/aflnet" @.&amp;gt;; 发送时间:&amp;nbsp;2023年5月7日(星期天) 中午1:16 @.&amp;gt;; @.&amp;gt;;"State @.&amp;gt;; 主题:&amp;nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96) I also encountered this problem, and I tried to reinstall it, but I have not tested a virtual machine. Did you solve this problem? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&amp;gt; 
    
 Thank you for your suggestion. I have also successfully solved this problem

**Comment by mboehme** [comment]
Yeah. That shouldn't be happening. If you know what is the reason, a PR will be much appreciated!

**Comment by chengzicmj** [comment]
I also think this shouldn't happen, but sorry I didn't find out why.
I also think this shouldn't happen, but sorry I didn't find out why.

ccc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aflnet/aflnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午5:17
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [aflnet/aflnet] Unable to see AFLNet's options. (Issue #96)





 
Yeah. That shouldn't be happening. If you know what is the reason, a PR will be much appreciated!
